_wandb:
    value:
        cli_version: 0.25.0
        e:
            2z6nbhtgqu14bz8cvpx8ckltjnkoer9g:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "16106127360"
                args:
                    - config/basic.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "152484945920"
                email: mcclellc@dickinson.edu
                executable: /Users/cobymcclellan/GitHub/Comp560-Latin-Addition-/venv/bin/python
                git:
                    commit: 4481176b1cf0446b08a5de52ba7a510eed80c751
                    remote: https://github.com/cmcclellan79/Comp560-Latin-Addition-
                host: Cobys-MacBook-Air-2.local
                memory:
                    total: "8589934592"
                os: macOS-13.5-arm64-arm-64bit
                program: /Users/cobymcclellan/GitHub/Comp560-Latin-Addition-/latin-numbers/../../comp560-nanoGPT/train.py
                python: CPython 3.9.6
                root: /Users/cobymcclellan/GitHub/Comp560-Latin-Addition-/latin-numbers
                startedAt: "2026-02-25T16:48:48.704291Z"
                writerId: 2z6nbhtgqu14bz8cvpx8ckltjnkoer9g
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.9.6
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 64
compile:
    value: false
dataset:
    value: basic
decay_lr:
    value: true
device:
    value: cpu
dropout:
    value: 0.1
dtype:
    value: float16
eval_interval:
    value: 100
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 40
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 10
lr_decay_iters:
    value: 2000
max_iters:
    value: 200
min_lr:
    value: 0.0001
n_embd:
    value: 128
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out
wandb_log:
    value: true
wandb_project:
    value: comp560-latin-numbers
wandb_run_name:
    value: basic-200-iters-test
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
